import Link from "next/link";
import { CadenceMark } from "@/components/CadenceMark";

export const metadata = {
  title: "Terms of Service — Cadence",
  description: "The terms for using Cadence, an AI assistant for Google Calendar.",
};

const UPDATED = "1 October 2026";
const CONTACT = "zahraelair17@gmail.com";

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-2">
      <h2 className="text-lg font-medium">{title}</h2>
      <div className="space-y-2 text-sm text-muted-foreground">{children}</div>
    </section>
  );
}

export default function TermsPage() {
  return (
    <div className="flex min-h-full flex-col">
      <header className="border-b">
        <div className="mx-auto flex max-w-3xl items-center justify-between px-4 py-3">
          <Link href="/" className="flex items-center gap-2 font-semibold tracking-tight">
            <CadenceMark className="h-8 w-8" /> Cadence
          </Link>
          <Link href="/" className="text-sm text-muted-foreground hover:text-foreground">Home</Link>
        </div>
      </header>

      <main className="mx-auto w-full max-w-3xl flex-1 space-y-8 px-4 py-12">
        <div className="space-y-1">
          <h1 className="text-3xl font-semibold tracking-tight">Terms of Service</h1>
          <p className="text-sm text-muted-foreground">Last updated: {UPDATED}</p>
        </div>

        <p className="text-sm text-muted-foreground">
          These terms govern your use of Cadence (&ldquo;the Service&rdquo;), an AI assistant that summarizes your
          Google Calendar and helps you manage events. By signing in and using the Service, you agree to these terms.
          If you do not agree, please do not use the Service.
        </p>

        <Section title="The service">
          <p>
            Cadence connects to your Google Calendar to generate summaries of your schedule and to create, update, or
            delete events at your request. It is a free personal project provided for your convenience.
          </p>
        </Section>

        <Section title="Your account and authorization">
          <p>
            You need a Google account to use Cadence, and you authorize it to access your calendar through Google&rsquo;s
            sign-in. You are responsible for keeping your Google account secure. You may withdraw this authorization at
            any time from your{" "}
            <a className="underline hover:text-foreground" href="https://myaccount.google.com/permissions" target="_blank" rel="noreferrer">
              Google Account permissions
            </a>
            .
          </p>
        </Section>

        <Section title="Changes to your calendar">
          <p>
            Cadence only creates, updates, or deletes an event after you explicitly confirm the action in the app. You
            are responsible for reviewing each change before confirming it and for the changes you confirm.
          </p>
        </Section>

        <Section title="Acceptable use">
          <p>
            Use the Service only for lawful purposes and only with calendars you are authorized to access. Do not attempt
            to disrupt, abuse, reverse-engineer, or gain unauthorized access to the Service or the accounts of others.
          </p>
        </Section>

        <Section title="AI-generated content">
          <p>
            Summaries and chat responses are generated by third-party AI models and may be inaccurate or incomplete.
            Treat them as assistance, not as authoritative records — always verify against your actual calendar before
            relying on them.
          </p>
        </Section>

        <Section title="Availability and &ldquo;as is&rdquo;">
          <p>
            The Service is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo;, without warranties of any kind,
            express or implied. It may change, be interrupted, or be discontinued at any time without notice, and it
            relies on third-party services that may themselves be unavailable.
          </p>
        </Section>

        <Section title="Limitation of liability">
          <p>
            To the fullest extent permitted by law, Cadence and its developer are not liable for any indirect,
            incidental, or consequential damages, or for any loss of data or calendar changes, arising from your use of
            the Service.
          </p>
        </Section>

        <Section title="Third-party services">
          <p>
            Cadence relies on Google (for sign-in and calendar access) and on an AI provider (Google Gemini, Groq,
            Mistral, or OpenRouter) to function. Your use of those services is also governed by their own terms and
            policies. See our{" "}
            <Link className="underline hover:text-foreground" href="/privacy">Privacy Policy</Link> for how data is handled.
          </p>
        </Section>

        <Section title="Changes to these terms">
          <p>
            These terms may be updated from time to time. Continued use of the Service after a change means you accept
            the updated terms. The &ldquo;last updated&rdquo; date above reflects the current version.
          </p>
        </Section>

        <Section title="Contact">
          <p>Questions about these terms? Contact {CONTACT}.</p>
        </Section>
      </main>

      <footer className="border-t">
        <div className="mx-auto flex max-w-3xl items-center justify-between px-4 py-6 text-sm text-muted-foreground">
          <span className="flex items-center gap-2"><CadenceMark className="h-6 w-6" /> Cadence</span>
          <div className="flex items-center gap-4">
            <Link href="/privacy" className="hover:text-foreground">Privacy</Link>
            <Link href="/" className="hover:text-foreground">Home</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
